"""add_payments

Revision ID: 5b7971de8f55
Revises: f27581e1e2fe
Create Date: 2026-05-28 21:51:47.868206
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5b7971de8f55"
down_revision: Union[str, None] = "f27581e1e2fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("amount_xof", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM("CINETPAY", "LOGGING", name="payment_provider"),
            nullable=False,
        ),
        sa.Column("provider_ref", sa.String(length=120), nullable=True),
        sa.Column("provider_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "INITIATED", "SUCCEEDED", "FAILED", "CANCELLED", name="payment_status"
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount_xof > 0", name="ck_payments_amount_positive"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_ref", name="uq_payments_provider_ref"),
    )
    op.create_index(op.f("ix_payments_goal_id"), "payments", ["goal_id"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_goal_id"), table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
