"""add_categories_transactions_pots_goals

Revision ID: f27581e1e2fe
Revises: 4a511e5bdb38
Create Date: 2026-05-28 21:10:39.495349
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f27581e1e2fe"
down_revision: Union[str, None] = "4a511e5bdb38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "kind", postgresql.ENUM("INCOME", "EXPENSE", name="category_kind"), nullable=False
        ),
        sa.Column("icon", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=9), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_index(
        "ix_categories_user_name_unique",
        "categories",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "savings_pots",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("balance_xof", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=9), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("balance_xof >= 0", name="ck_savings_pots_balance_non_negative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_savings_pots_user_id"), "savings_pots", ["user_id"], unique=False)
    op.create_index(
        "ix_savings_pots_user_name_unique", "savings_pots", ["user_id", "name"], unique=True
    )
    op.create_table(
        "goals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("savings_pot_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("target_amount_xof", sa.Integer(), nullable=False),
        sa.Column("current_amount_xof", sa.Integer(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("ACTIVE", "COMPLETED", "ABANDONED", name="goal_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_amount_xof >= 0", name="ck_goals_current_non_negative"),
        sa.CheckConstraint("target_amount_xof > 0", name="ck_goals_target_positive"),
        sa.ForeignKeyConstraint(["savings_pot_id"], ["savings_pots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_savings_pot_id"), "goals", ["savings_pot_id"], unique=False)
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("amount_xof", sa.Integer(), nullable=False),
        sa.Column(
            "kind", postgresql.ENUM("INCOME", "EXPENSE", "TRANSFER", name="tx_kind"), nullable=False
        ),
        sa.Column(
            "source",
            postgresql.ENUM(
                "MANUAL", "NOTIFICATION", "SMS", "MOBILE_MONEY_API", "BANK_API", name="tx_source"
            ),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=120), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("counterparty", sa.String(length=120), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount_xof > 0", name="ck_transactions_amount_positive"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_occurred_at"), "transactions", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index(
        "ix_transactions_user_occurred_at", "transactions", ["user_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_transactions_user_source_ref_unique",
        "transactions",
        ["user_id", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transactions_user_source_ref_unique",
        table_name="transactions",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index("ix_transactions_user_occurred_at", table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_occurred_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_savings_pot_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index("ix_savings_pots_user_name_unique", table_name="savings_pots")
    op.drop_index(op.f("ix_savings_pots_user_id"), table_name="savings_pots")
    op.drop_table("savings_pots")
    op.drop_index(
        "ix_categories_user_name_unique",
        table_name="categories",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
